version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Pharmacy-Recommendation
    overwrite: yes
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user